[package]
name = "drone-rust"
version = "0.1.0"
edition = "2021"
authors = ["Carson Gee <x@carsongee.com"]


[dependencies]
clap = { version = "4.3.0", features = ["derive", "env"] }
json = "0.12.4"

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"
